# -*- coding: utf-8 -*-
"""BoW_3_less_common.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qcw9T7YbKbuLXQaEwwwI4ufLBetYQma3
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction.text import TfidfVectorizer
import re

df = pd.read_csv('rare_df.csv')
df.head()

"""# Bag-of-Words at Sentence Level"""

# Convert text to lowercase
df['TEXT'] = df['TEXT'].str.lower()

# split into x and y
texts = df['TEXT']
y = df['DIAGNOSIS']

# split data into training and testing sets
texts_train, texts_test, y_train, y_test = train_test_split(texts, y, test_size=0.2, random_state=42)

# split data into training and validation sets
texts_train, texts_validation, y_train, y_validation = train_test_split(texts_train, y_train, test_size=0.2, random_state=42)

train_set = pd.concat((texts_train,y_train),axis=1)

# transform the text data into bag-of-words at sentence level
# filter out stop words
count_vectorizer = CountVectorizer(stop_words='english')
X_bow_training = count_vectorizer.fit_transform(texts_train)
X_bow_validation = count_vectorizer.transform(texts_validation)
X_bow_test = count_vectorizer.transform(texts_test)

# Initialize classifiers
models = {
    'Binary Naive Bayes': BernoulliNB(),
    'Logistic Regression': LogisticRegression()
}

# print a classifcation report for each model in models
for model_name, model in models.items():
    model.fit(X_bow_training, y_train)
    y_pred = model.predict(X_bow_test)
    print(f"\nClassification Report for {model_name}:")
    print(classification_report(y_test, y_pred, target_names=['RENAL FAILURE', 'STROKE', 'WOUND INFECTION']))

"""# Bag-of-Words Using N-Gram
### aka looking at neighboring words
"""

# read data and convert to all lowercase
data = pd.read_csv('rare_df.csv')
data['TEXT'] = data['TEXT'].str.lower()

# split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data['TEXT'], data['DIAGNOSIS'], test_size=0.2, random_state=42)

# Initialize CountVectorizer with n-gram range for bigrams and filter out stop words
vectorizer = CountVectorizer(ngram_range=(2, 2), stop_words='english')

# Fit and transform the training data, then transform the test data
X_train_bigrams = vectorizer.fit_transform(X_train)
X_test_bigrams = vectorizer.transform(X_test)

# Initialize classifiers
models = {
    'Binary Naive Bayes': BernoulliNB(),
    #'SVM': SVC(),
    'Logistic Regression': LogisticRegression()
}

# print a classifcation report for each model in models
for model_name, model in models.items():
    model.fit(X_train_bigrams, y_train)
    y_pred = model.predict(X_test_bigrams)
    print(f"\nClassification Report for {model_name}:")
    print(classification_report(y_test, y_pred, target_names=['RENAL FAILURE', 'STROKE', 'WOUND INFECTION']))

"""# Symptom Severity"""

# Define a function to handle severity weights
def handle_severity(text):
    severity_map = {
        "mild": 1,
        "moderate": 2,
        "severe": 3,
        "critical": 4,
        "life-threatening": 5
    }
    words = text.split()
    weighted_text = []
    for word in words:
        if word in severity_map:
            weighted_text.extend([word] * severity_map[word])  # Repeat word based on severity weight
        else:
            weighted_text.append(word)
    return " ".join(weighted_text)

"""# Synonyms and Medical Terminology"""

# Custom Stopwords
custom_stopwords = set([
    "patient", "reported", "history", "include", "related",
    "observed", "symptoms", "along", "with", "of", "and"
])

# Dictionary of synonymous medical terminology
synonym_dict = {
    "heart attack": "myocardial infarction",
        "mi": "myocardial infarction",
        "myocardial infarction": "myocardial infarction",
        "chf": "congestive heart failure",
        "heart failure": "congestive heart failure",
        "cardiac failure": "congestive heart failure",
        "lung infection": "pneumonia",
        "respiratory infection": "pneumonia",
        "septicemia": "sepsis",
        "blood infection": "sepsis",
        "systemic infection": "sepsis",
        "shortness of breath": "dyspnea",
        "dyspnea": "dyspnea",
        "cp": "chest pain",
        "chest discomfort": "chest pain",
        "fever": "pyrexia",
        "pyrexia": "pyrexia",
        "low blood pressure": "hypotension",
        "high blood pressure": "hypertension",
        "htn": "hypertension",
        "elevated bp": "hypertension",
        "low oxygen": "hypoxia",
        "oxygen deficiency": "hypoxia",
        "hypoxia": "hypoxia",
        "cardiac arrest": "heart failure",
        "shortness of breath": "dyspnea",
        "chest pain": "angina",
        "fatigue": "tiredness"

}

# Preprocessing Function
def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()

    # Replace synonyms
    for phrase, replacement in synonym_dict.items():
        text = re.sub(r'\b' + re.escape(phrase) + r'\b', replacement, text)

    # Remove custom stopwords
    words = text.split()
    words = [word for word in words if word not in custom_stopwords]

    return ' '.join(words)

# Load data
df = pd.read_csv('rare_df.csv')

# Apply synonym normalization and handle severity weights
df['TEXT'] = df['TEXT'].apply(preprocess_text)
#df['TEXT'] = df['TEXT'].apply(handle_severity) # does better without it???

# Split into features and labels
texts = df['TEXT']
y = df['DIAGNOSIS']

# Split data into training, validation, and testing sets
texts_train, texts_test, y_train, y_test = train_test_split(texts, y, test_size=0.2, random_state=42)
texts_train, texts_validation, y_train, y_validation = train_test_split(texts_train, y_train, test_size=0.2, random_state=42)

# TF-IDF Vectorization with Bigrams
tfidf_vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1, 2), max_df=0.7, min_df=5)
X_tfidf_train = tfidf_vectorizer.fit_transform(texts_train)
X_tfidf_test = tfidf_vectorizer.transform(texts_test)

# Initialize classifiers
models = {
    'Binary Naive Bayes': BernoulliNB(),
    'Logistic Regression': LogisticRegression(max_iter=1000, class_weight='balanced')
}

# Evaluate models
for model_name, model in models.items():
    model.fit(X_tfidf_train, y_train)
    y_pred = model.predict(X_tfidf_test)
    print(f"\nClassification Report for {model_name}:")
    print(classification_report(y_test, y_pred, target_names=['RENAL FAILURE', 'STROKE', 'WOUND INFECTION']))